version: '3.3'

services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 's_schema'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'abc123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/sp/mysql
    networks: 
      - app

  oauth2-server:
    image: oauth2-server
    build: ./oauth2-server
    volumes:
      - /var/lib/sp/oauth2-server:/var/lib/sp/oauth2-server/data
      - ~/.m2:/root/.m2
    ports:
      - '8081:8081'
    networks: 
      - app
    depends_on: 
      - mysql

  social-api:
    image: social-api
    build: ./social-api
    volumes:
      - /var/lib/sp/social-api:/var/lib/sp/social-api/data
      - ~/.m2:/root/.m2
    ports:
      - '8082:8082'
    networks: 
      - app
    depends_on: 
      - mysql

volumes:
  my-db:

networks:
  app: