version: '3.3'

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 's_schema'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'abc123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/sp/mysql
    networks: 
      - app

  redis:
    image: redis
    expose:
      - 6379
    networks: 
      - app

  oauth2-server:
    image: oauth2-server
    build: ./oauth2-server
    restart: always
    volumes:
      - ./oauth2-server/data
      - ~/.m2:/root/.m2
    ports:
      - '8081:8081'
    expose:
      - '8081'
    networks: 
      - app
    environment:
      WAIT_HOSTS: mysql:3306

  social-api:
    image: social-api
    build: ./social-api
    restart: always
    volumes:
      - ./social-api/data
      - ~/.m2:/root/.m2
    ports:
      - '8082:8082'
    expose:
      - '8082'
    networks: 
      - app

volumes:
  my-db:

networks:
  app: